### ISSUE TITLE
Analysis content not properly visible.

### ISSUE THREAD

**Issue by Kritika-Jha** [recodehive/Stackoverflow-Analysis#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The analysis part has a lighter background along with light font color making it difficult for users to read it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Bliss011** [comment]
Can you please assign this task to me. @sanjay-kv

**Comment by sanjay-kv** [comment]
this is already done, if not attach a screenshot for reference
