### ISSUE TITLE
[Feature Request]: Add a new customisation module in Streamlit web app

### ISSUE THREAD

**Issue by Shraman-jain** [recodehive/Stackoverflow-Analysis#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In this module I have decided that user can select two columns of their choice from the existing one and can plot those two columns in various types of charts or plots and can also download the charts which they have created. 
Please assign this issue to me and also add gssoc24 tag

### Use Case

They can get customised charts based on their research purposes 

### Benefits

Can help people with different requirements for their personal analysis.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Shraman-jain** [comment]
Thank You for assigning. I will finish as soon as possible

**Comment by Shraman-jain** [comment]
@sanjay-kv should i create a seperate web app or add a different page for the customization module and also i will be trying to build a module which works like tableau in which user can plot different charts with different columns so i think that should not be a level1 issue!. Rest you can check after I open a PR and label accordingly. Thanks

**Comment by sanjay-kv** [comment]
In the existing webapp , I will look at your work on PR and add levels accordingly.
