### ISSUE TITLE
[Feature Request]: Adding hover effect on select year dropdown

### ISSUE THREAD

**Issue by Rajul-29** [recodehive/Stackoverflow-Analysis#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a hover effect to the "Select Year" dropdown in the user interface, making the dropdown menu items visually highlight when hovered over to improve user experience and navigation clarity.

### Use Case

This feature would enhance the project's usability by providing visual feedback to users as they navigate the dropdown menu, making it easier to identify and select the desired year. This improves the overall user experience by making the interface more intuitive and responsive.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Rajul-29** [comment]
Hey @sanjay-kv!
I am a contributor for GSSOC'24, Can you please assign me this issue
Thank you

**Comment by tkshsbcue** [comment]
Hey I would like to work on this issue
