### ISSUE TITLE
[Feature Request]: Estimate Frequency of Updating Resume

### ISSUE THREAD

**Issue by ranamanish674zu** [recodehive/Stackoverflow-Analysis#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Predict how frequently a respondent updates their resume based on their job satisfaction, career satisfaction, and job-seeking behavior.
Dataset->survey_results_public_2019.csv

### Use Case

it will help to understand job availability to job seekers

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
Im not sure is there any relevant data to work on this, could you explain in details what all variables been used.

**Comment by ranamanish674zu** [comment]
> Im not sure is there any relevant data to work on this, could you explain in details what all variables been used.

@sanjay-kv sir there is feature "ResumeUpdate" in dataset , so based open different feature-> company and JobSat,CareerSat ,LastHireDate , jobFactors ,MgrIdiot, MgrMoney, MgrWant ,WorkWeekHrs, SOPartFreq so on , we can analysis how user is updating the resume according to the situation
