### ISSUE TITLE
[Feature Request]: Predict Longevity at Current Job

### ISSUE THREAD

**Issue by ranamanish674zu** [recodehive/Stackoverflow-Analysis#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Estimating how long a respondent is likely to stay at their current job based on their job satisfaction, career goals, and manager satisfaction.

### Use Case

i will help company to see at which position the people would like to stay and at which company (which type company)

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ranamanish674zu** [comment]
Dataset->survey_results_public_2019

**Comment by sanjay-kv** [comment]
which variables gonna use there?

**Comment by ranamanish674zu** [comment]
sir we can use JobSat,CareerSat  ,LastHireDate , jobFactors ,MgrIdiot, MgrMoney,  MgrWant ,WorkWeekHrs, SOPartFreq
