### ISSUE TITLE
[Feature]: Analyze the impact of higher education on the salary of the surveyed developers of 2018.

### ISSUE THREAD

**Issue by Nidhi-Satyapriya** [recodehive/Stackoverflow-Analysis#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature aims to analyze the correlation between higher education levels and the salaries of developers surveyed in 2018. The analysis will help understand how different educational qualifications influence earning potential in the developer community.

**Objectives**
1) To process data from the 2018 survey.
2) To visualize the relationship between education and salary using charts and graphs.

**Deliverables**
1) Visualizations illustrating the impact of higher education on salaries.
2) A summary report detailing the findings and any noticeable trends or insights.

**Technical Requirements**
1) Data cleaning and preprocessing using Python (Pandas, NumPy).
2) Statistical analysis using Python (Statsmodels).
3) Data visualization using Python (Matplotlib, Seaborn).
4) Documentation of the analysis process and findings.

### Use Case

1) As a developer/student considering further education, I want to know the potential salary benefits of obtaining higher educational qualifications.
2) As a data analyst, I want to see a detailed breakdown of developer salaries based on their education levels so that I can identify trends and patterns.
3) As a stakeholder, I want to understand how higher education impacts salaries in the developer community to make informed decisions about hiring and salary structuring.

### Benefits

1. Career Guidance for Developers/Students
2. Understanding Market Trends
3. Content for Educational Platforms for career counseling services 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Nidhi-Satyapriya** [comment]
@sanjay-kv kindly look into this and assign it to me.

**Comment by Nidhi-Satyapriya** [comment]
@sanjay-kv I made a PR. It is now open to your recommendations and review.

**Comment by sanjay-kv** [comment]
will review it

**Comment by Nidhi-Satyapriya** [comment]
Did you have a look? @sanjay-kv
