### ISSUE TITLE
[Bug]: Enable code to run outside Google colab

### ISSUE THREAD

**Issue by shristirwt** [recodehive/Stackoverflow-Analysis#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I ran the code on my local system it raised an error of importing google colab. I wanted it to run outside google colab as well so I modified the code for that. Please assign it to me
![Screenshot 2024-10-02 230521](https://github.com/user-attachments/assets/4d5e79ba-0ee5-463d-91d2-1d9c6e6ae650)

### Add ScreenShots

![Screenshot 2024-10-02 230742](https://github.com/user-attachments/assets/0f676dae-39da-4cbb-a41e-3aa1c8f971bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by AnujSaha0111** [comment]
I want to work on this issue. Can you please assign it to me?

**Comment by prisha-sh** [comment]
Hey I'm interested please assign me, ill share my proposed solution as soon as u ping me !!
