### ISSUE TITLE
Adding language traslator

### ISSUE THREAD

**Issue by Aditijainnn** [recodehive/Stackoverflow-Analysis#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

So adding language switcher so that people can switch to other languages also

### Use Case

please assign this to me under gssoc ext and hacktoberfest

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!
