### ISSUE TITLE
[Bug]: Error Handling in Data Loading

### ISSUE THREAD

**Issue by Ankush0286** [recodehive/Stackoverflow-Analysis#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## When the Error Message Shows
The error messages will be displayed in the following scenario:

**Error During Data Loading**: 
- If the file exists but there is an issue when attempting to read the data (within the `try` block), the following scenarios might occur:
  - The file is in an unsupported format (e.g., it’s not a valid CSV).
  - The file is corrupted or malformed.
  - There are permission issues that prevent reading the file.

In this case, the error message will indicate that an error occurred while loading the data, providing more context such as: An error occurred while loading data: specific error message from the exception

### Conclusion
This error handling mechanism ensures that users receive clear and informative feedback, allowing them to diagnose and rectify issues efficiently.

### Add ScreenShots
![Screenshot_error_handling_sj](https://github.com/user-attachments/assets/60b1d679-c52a-4c67-9006-1efbec9473cf)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!
