### ISSUE TITLE
[Documentation Update]: Adding importance of data cleaning  and tools used for it in the readme  

### ISSUE THREAD

**Issue by shravya312** [recodehive/Stackoverflow-Analysis#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Data cleaning is one of the important part of the machine learning  project

### Suggested Change

During surveys there are possibillity of duplicate data.Its a waste of resources to make predictions on the same data.
Sometimes Details told to fill in the survey will be left blank thats call NULL. these should be treated before starting predicted 
So people should be aware of data cleaning

### Rationale

It help people to understand why data cleaning's important and gain insights on how to do it 

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
i think the current readmen is pretty long enough, i dont think this is required. feel free to raise more issues.

**Comment by shravya312** [comment]
Okay sure

**Comment by Ayesha480** [comment]
please assign the lable i want to work on it
