### ISSUE TITLE
[Feature Request]: Change font color for soothing user experience

### ISSUE THREAD

**Issue by JOSHITHA6** [recodehive/Stackoverflow-Analysis#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I have observed that the red-lined font looks like a warning kind of answer, very disturbing to any user. I would love to solve this issue. Please assign this task to me under gssoc'24 extd and hacktoberfest @s

![Screenshot (175)](https://github.com/user-attachments/assets/867e8a5a-39e4-452a-9eea-07d2ba78a7bf)

### Use Case

Better experience and more impact.

### Benefits

This feature would definitely improve user experience. 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by anchalchaturvedi08** [comment]
Hello PA, I want to work on this issue. Can you assign it to me?

**Comment by JOSHITHA6** [comment]
I'm working on this

**Comment by JOSHITHA6** [comment]
@sanjay-kv I have solved the issue. Please check out.
