### ISSUE TITLE
[Documentation Update]: Job satisfaction analysis model update

### ISSUE THREAD

**Issue by lkksharma** [recodehive/Stackoverflow-Analysis#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The Job satisfaction analysis only uses one model i.e. the RandomForest to predict the output. The main python notebook itself, has more detailed models listed.

### Suggested Change

I wish to add other models and also include the comparison in accuracy amongst those models so as to give a better picture along with a more accurate data prediction. My aim would be mainly to add SVM and Logistic Regression to the testing and try other models as experimentation if time permits along with hyper-parameter tuning suited for the current computational capacity.

### Rationale

People visiting the job satisfactory survey analysis might think that the file is not that well worked on. ALong with that the predictions that file offers is not tested, which it would be if the above issue is implemented.

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
This should be the integration to existing streamlit not a new one,
