### ISSUE TITLE
[Feature Request]: Add some more charts for better understanding for Job Satisfaction Analysis

### ISSUE THREAD

**Issue by SimranShaikh20** [recodehive/Stackoverflow-Analysis#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Feature Description
Data Analysis/Daily News and Stock Data Analysis/DailyNews.ipynb

Hi, I am Simran Shaikh. I’ve been reviewing the project as part of my contribution to GSSoC Extended 24 and noticed that the code performs by adding more charts for better understanding we can used different library of python like seaborn or matplotlib . By using this library its easy to understand Job Satisfaction Analysis . Also we can include some data cleaning concept for more accurate and efficient data. As  i had find an exixting issue there is no more charts  .

This would help increase in more visualization . I would like to work on this.
If you like this idea,  assign the task to me and add the corresponding charts to it.
Thank you for your time and consideration!

### Use Case

Data visualization give more effectiveness then code . For the data analyst point of view and make easy way for end user or non technical person to understand in easy way .

### Benefits

Easy to understand

### Priority

@sanjay-kv 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
This should be on the exsiting streamlit application

**Comment by SimranShaikh20** [comment]
@sanjay-kv  
I have added PR .
Can you please change the level of label i have performed is very well and in efficient way . 
You can see  my work.

**Comment by SimranShaikh20** [comment]
@sanjay-kv 
Thanks for level 2 label
