### ISSUE TITLE
[Bug]: Deprecation Warning: Use of fillna(method='ffill') Deprecated in Pandas

### ISSUE THREAD

**Issue by shristirwt** [recodehive/Stackoverflow-Analysis#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While executing the code it displayed an error that Series.fillna is deprecated and we need to use obj.ffill or obj.bfill instead

![Screenshot 2024-10-14 211743](https://github.com/user-attachments/assets/d7efafdf-e157-4228-a2dc-1577d1654aea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by vishnumur777** [comment]
Can you assign me to work on this issue?

**Comment by shristirwt** [comment]
@sanjay-kv Please assign #396 and #397 also
