### ISSUE TITLE
[Feature Request]: Add some charts for better understanding for opensource_analysis  

### ISSUE THREAD

**Issue by SimranShaikh20** [recodehive/Stackoverflow-Analysis#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Feature Description
opensource_analysis/opensource_analysis.ipynb

Hi, I am Simran Shaikh. I’ve been reviewing the project as part of my contribution to GSSoC Extended 24 and noticed that the code performs by adding more charts for better understanding we can used different library of python like seaborn or matplotlib . By using this library its easy to understand  opensource  Analysis . Also we can include some data cleaning concept for more accurate and efficient data. As i had find an exixting issue there is no more charts .We can also visualize what are contibuter review and what are there suggestion or feedback for open source program.

This would help increase in more visualization . I would like to work on this.
If you like this idea, assign the task to me and add the corresponding charts to it.
Thank you for your time and consideration!

Priority
@sanjay-kv

### Use Case

Use Case
Data visualization give more effectiveness then code . For the data analyst point of view and make easy way for end user or non technical person to understand in easy way .

### Benefits

Benefits
Easy to understand

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by dimeneman** [comment]
I want to contribute to it .
