### ISSUE TITLE
[Bug]: Add correct file path

### ISSUE THREAD

**Issue by shristirwt** [recodehive/Stackoverflow-Analysis#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The file path used in Portfolio_Optimization_Using_Genetic_Algorithm.ipynb is incorrect

![Screenshot 2024-10-19 193914](https://github.com/user-attachments/assets/10f99edc-8a8e-4c3e-ab70-3d79742b334d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
@shristirwt let me know any guidelines need on the mentorship

**Comment by shristirwt** [comment]
> @shristirwt let me know any guidelines need on the mentorship

sure sir
