### ISSUE TITLE
[Bug]: App Deployment Link Not Working – Showing Errors on Access

### ISSUE THREAD

**Issue by shristirwt** [recodehive/Stackoverflow-Analysis#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Issue Description:
The app link provided on the repo is not working. On accessing the link, it displays some errors instead of working properly

The app link is as follows:
stackoverflow-analysis.streamlit.app/

Expected behaviour:
The app should load without errors and function as intended.

Error in deployment:
![Screenshot 2024-10-23 202017](https://github.com/user-attachments/assets/467ee716-009d-40f2-a474-e421e44bba97)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [ ] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by shristirwt** [comment]
Sir I don't want to work on this issue I had created it for other contributors who can work upon this

**Comment by Aditya-NV-06** [comment]
Can I work on this issue
