### ISSUE TITLE
[Bug]: Incorrect file path 

### ISSUE THREAD

**Issue by shristirwt** [recodehive/Stackoverflow-Analysis#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The file path provided in the code is incorrect due to which the code cannot be executed properly.
![Screenshot 2024-10-23 203126](https://github.com/user-attachments/assets/22eb686d-c560-422e-85d6-f90698769156)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
@shristirwt activate your sponser badge. i want to sponser you

**Comment by shristirwt** [comment]
> @shristirwt activate your sponser badge. i want to sponser you

Sir I have setup my sponsors profile. I was working on enabling my sponsor button but I could not understand much. I have created a FUNDING.yml file but for now the sponsor button has not been enabled
