### ISSUE TITLE
[Bug]: PlatformWorkedWith column doesn't exist

### ISSUE THREAD

**Issue by shristirwt** [recodehive/Stackoverflow-Analysis#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While executing the code the error of not finding the column named PlatformWorkedWith occured
![Screenshot 2024-11-01 191741](https://github.com/user-attachments/assets/bc4a94b0-7f35-4068-823d-ffc73aa5a0fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
@aimanrazia This is already assigned and person is working on.
